### ISSUE TITLE
Resolved aqinstall spec (6.7.0) not available

### ISSUE THREAD

**Issue by silvaronald** [robocin/scripts-ubuntu-common#8]
No momento, ao instalar o qt por meio do arquivo setup.py, automaticamente ele é convertido para a versão 6.7.0, aparecendo a seguinte mensagem:

> /tmp/qt /home/ronald/Coding/RoboCIn/ssl-unification/scripts
> INFO    : aqtinstall(aqt) v3.1.11 on Python 3.10.12 [CPython GCC 11.4.0]
> INFO    : Resolved spec '6' to 6.7.0
> WARNING : Specified Qt version "6.7.0" did not exist when this version of aqtinstall was released. This may not install properly, but we will try our best.
> ERROR   : The packages ['qt_base'] were not found while parsing XML of package information!

 Porém, ela não está disponível no projeto, e ao usar o comando cmake o seguinte erro é gerado:
 
![image](https://github.com/robocin/scripts-ubuntu-common/assets/52102394/e414e4c2-787d-4697-bfb5-e2ac28102164)

Nesse sentido, uma solução apontada por @Riei-Joaquim foi alterar [esta linha de código](https://github.com/robocin/scripts-ubuntu-common/blob/b987377c8ee6f3b8e5c8d37015408e3d4bb4cea9/qt.sh#L19) para indicar a versão '6.4' em vez de '6'.

**Comment by Riei-Joaquim** [comment]
@joseviccruz  acho que podemos deixar batido como 6.4 para não ter trabalho extra com a lib em momentos futuros

**Comment by joseviccruz** [comment]
O primeiro argumento do script de instalação é a versão. Concordo em deixar fixa, no setup.py só fazer ele passar o 1o argumento como fixo ou mudar o arg default pra 6.4.0

**Comment by ersaraujo** [comment]
https://github.com/robocin/scripts-ubuntu-common/pull/9
